"""Load 18 illustrative demo deals (6 per sub-asset class) through the API.

These are SYNTHETIC: fictional property names, with rents, expenses, cap
rates and financing calibrated to the ranges in seed_reference_data.py's
CBRE H1 2026 / Berkadia 2026 sources. They are not real listings.

Goes through the public REST API rather than the database, so no DB
credentials are needed. Skips any deal whose name already exists, so it is
safe to re-run.

Usage:
    python seed_demo_deals.py https://dealrank-api.onrender.com
    python seed_demo_deals.py http://localhost:8000
"""

import json
import sys
import urllib.request

DEMO_DEALS = [
    {
        "name": "Campus Edge Commons",
        "sub_asset_class": "student_housing",
        "leasing_mode": "per_bed",
        "unit_count": None,
        "monthly_rent_per_unit": None,
        "bed_count": 320,
        "monthly_rent_per_bed": "795.00",
        "vacancy_rate": "0.06",
        "other_income_annual": "35200.00",
        "opex_annual": "912000.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.03",
        "lease_expiration_month": 8,
        "turnover_cost_per_unit_or_bed": "350.00",
        "annual_turnover_rate": "0.85",
        "purchase_price": "31110000.00",
        "closing_costs": "622200.00",
        "loan_amount": "19290000.00",
        "interest_rate": "0.064",
        "amortization_years": 30,
        "hold_period_years": 7,
        "exit_cap_rate": "0.0650",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Gameday Flats",
        "sub_asset_class": "student_housing",
        "leasing_mode": "per_bed",
        "unit_count": None,
        "monthly_rent_per_unit": None,
        "bed_count": 412,
        "monthly_rent_per_bed": "880.00",
        "vacancy_rate": "0.05",
        "other_income_annual": "57680.00",
        "opex_annual": "1277200.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.035",
        "lease_expiration_month": 8,
        "turnover_cost_per_unit_or_bed": "375.00",
        "annual_turnover_rate": "0.88",
        "purchase_price": "48730000.00",
        "closing_costs": "974600.00",
        "loan_amount": "29240000.00",
        "interest_rate": "0.0625",
        "amortization_years": 30,
        "hold_period_years": 7,
        "exit_cap_rate": "0.0605",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "The Quad at Riverside",
        "sub_asset_class": "student_housing",
        "leasing_mode": "per_bed",
        "unit_count": None,
        "monthly_rent_per_unit": None,
        "bed_count": 236,
        "monthly_rent_per_bed": "690.00",
        "vacancy_rate": "0.09",
        "other_income_annual": "18880.00",
        "opex_annual": "590000.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.025",
        "lease_expiration_month": 8,
        "turnover_cost_per_unit_or_bed": "325.00",
        "annual_turnover_rate": "0.8",
        "purchase_price": "17360000.00",
        "closing_costs": "347200.00",
        "loan_amount": "11280000.00",
        "interest_rate": "0.0675",
        "amortization_years": 30,
        "hold_period_years": 6,
        "exit_cap_rate": "0.0710",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Stadium Row Lofts",
        "sub_asset_class": "student_housing",
        "leasing_mode": "per_bed",
        "unit_count": None,
        "monthly_rent_per_unit": None,
        "bed_count": 288,
        "monthly_rent_per_bed": "940.00",
        "vacancy_rate": "0.07",
        "other_income_annual": "43200.00",
        "opex_annual": "964800.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.035",
        "lease_expiration_month": 8,
        "turnover_cost_per_unit_or_bed": "400.00",
        "annual_turnover_rate": "0.9",
        "purchase_price": "36290000.00",
        "closing_costs": "725800.00",
        "loan_amount": "21050000.00",
        "interest_rate": "0.0615",
        "amortization_years": 30,
        "hold_period_years": 7,
        "exit_cap_rate": "0.0580",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Oak Hall Residences",
        "sub_asset_class": "student_housing",
        "leasing_mode": "per_bed",
        "unit_count": None,
        "monthly_rent_per_unit": None,
        "bed_count": 180,
        "monthly_rent_per_bed": "725.00",
        "vacancy_rate": "0.08",
        "other_income_annual": "16200.00",
        "opex_annual": "468000.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.025",
        "lease_expiration_month": 8,
        "turnover_cost_per_unit_or_bed": "325.00",
        "annual_turnover_rate": "0.82",
        "purchase_price": "14940000.00",
        "closing_costs": "298800.00",
        "loan_amount": "9560000.00",
        "interest_rate": "0.066",
        "amortization_years": 30,
        "hold_period_years": 5,
        "exit_cap_rate": "0.0675",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Brickyard Student Living",
        "sub_asset_class": "student_housing",
        "leasing_mode": "per_bed",
        "unit_count": None,
        "monthly_rent_per_unit": None,
        "bed_count": 364,
        "monthly_rent_per_bed": "830.00",
        "vacancy_rate": "0.06",
        "other_income_annual": "43680.00",
        "opex_annual": "1073800.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.03",
        "lease_expiration_month": 8,
        "turnover_cost_per_unit_or_bed": "350.00",
        "annual_turnover_rate": "0.86",
        "purchase_price": "38440000.00",
        "closing_costs": "768800.00",
        "loan_amount": "23450000.00",
        "interest_rate": "0.063",
        "amortization_years": 30,
        "hold_period_years": 8,
        "exit_cap_rate": "0.0630",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Willowbrook Gardens",
        "sub_asset_class": "suburban_garden",
        "leasing_mode": "per_unit",
        "unit_count": 180,
        "monthly_rent_per_unit": "1450.00",
        "bed_count": None,
        "monthly_rent_per_bed": None,
        "vacancy_rate": "0.05",
        "other_income_annual": "108000.00",
        "opex_annual": "1062000.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.03",
        "lease_expiration_month": 6,
        "turnover_cost_per_unit_or_bed": "650.00",
        "annual_turnover_rate": "0.48",
        "purchase_price": "36390000.00",
        "closing_costs": "727800.00",
        "loan_amount": "22560000.00",
        "interest_rate": "0.061",
        "amortization_years": 30,
        "hold_period_years": 7,
        "exit_cap_rate": "0.0575",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Maple Ridge Apartments",
        "sub_asset_class": "suburban_garden",
        "leasing_mode": "per_unit",
        "unit_count": 264,
        "monthly_rent_per_unit": "1325.00",
        "bed_count": None,
        "monthly_rent_per_bed": None,
        "vacancy_rate": "0.06",
        "other_income_annual": "142560.00",
        "opex_annual": "1452000.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.028",
        "lease_expiration_month": 6,
        "turnover_cost_per_unit_or_bed": "600.00",
        "annual_turnover_rate": "0.5",
        "purchase_price": "44860000.00",
        "closing_costs": "897200.00",
        "loan_amount": "29160000.00",
        "interest_rate": "0.064",
        "amortization_years": 30,
        "hold_period_years": 7,
        "exit_cap_rate": "0.0610",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Cedar Point Villas",
        "sub_asset_class": "suburban_garden",
        "leasing_mode": "per_unit",
        "unit_count": 120,
        "monthly_rent_per_unit": "1575.00",
        "bed_count": None,
        "monthly_rent_per_bed": None,
        "vacancy_rate": "0.045",
        "other_income_annual": "86400.00",
        "opex_annual": "768000.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.032",
        "lease_expiration_month": 6,
        "turnover_cost_per_unit_or_bed": "700.00",
        "annual_turnover_rate": "0.45",
        "purchase_price": "28360000.00",
        "closing_costs": "567200.00",
        "loan_amount": "17020000.00",
        "interest_rate": "0.0595",
        "amortization_years": 30,
        "hold_period_years": 6,
        "exit_cap_rate": "0.0540",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Sycamore Crossing",
        "sub_asset_class": "suburban_garden",
        "leasing_mode": "per_unit",
        "unit_count": 340,
        "monthly_rent_per_unit": "1240.00",
        "bed_count": None,
        "monthly_rent_per_bed": None,
        "vacancy_rate": "0.07",
        "other_income_annual": "163200.00",
        "opex_annual": "1768000.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.025",
        "lease_expiration_month": 6,
        "turnover_cost_per_unit_or_bed": "575.00",
        "annual_turnover_rate": "0.52",
        "purchase_price": "50820000.00",
        "closing_costs": "1016400.00",
        "loan_amount": "33540000.00",
        "interest_rate": "0.066",
        "amortization_years": 30,
        "hold_period_years": 8,
        "exit_cap_rate": "0.0635",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Heritage Park Townhomes",
        "sub_asset_class": "suburban_garden",
        "leasing_mode": "per_unit",
        "unit_count": 96,
        "monthly_rent_per_unit": "1690.00",
        "bed_count": None,
        "monthly_rent_per_bed": None,
        "vacancy_rate": "0.04",
        "other_income_annual": "76800.00",
        "opex_annual": "652800.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.035",
        "lease_expiration_month": 6,
        "turnover_cost_per_unit_or_bed": "725.00",
        "annual_turnover_rate": "0.42",
        "purchase_price": "25790000.00",
        "closing_costs": "515800.00",
        "loan_amount": "14960000.00",
        "interest_rate": "0.0585",
        "amortization_years": 30,
        "hold_period_years": 5,
        "exit_cap_rate": "0.0515",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Pinecrest at Lakeview",
        "sub_asset_class": "suburban_garden",
        "leasing_mode": "per_unit",
        "unit_count": 216,
        "monthly_rent_per_unit": "1395.00",
        "bed_count": None,
        "monthly_rent_per_bed": None,
        "vacancy_rate": "0.055",
        "other_income_annual": "120960.00",
        "opex_annual": "1231200.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.03",
        "lease_expiration_month": 6,
        "turnover_cost_per_unit_or_bed": "625.00",
        "annual_turnover_rate": "0.49",
        "purchase_price": "40740000.00",
        "closing_costs": "814800.00",
        "loan_amount": "25670000.00",
        "interest_rate": "0.0625",
        "amortization_years": 30,
        "hold_period_years": 7,
        "exit_cap_rate": "0.0585",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Meridian Urban Tower",
        "sub_asset_class": "urban_midrise",
        "leasing_mode": "per_unit",
        "unit_count": 210,
        "monthly_rent_per_unit": "2350.00",
        "bed_count": None,
        "monthly_rent_per_bed": None,
        "vacancy_rate": "0.06",
        "other_income_annual": "315000.00",
        "opex_annual": "2058000.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.035",
        "lease_expiration_month": 7,
        "turnover_cost_per_unit_or_bed": "900.00",
        "annual_turnover_rate": "0.52",
        "purchase_price": "76030000.00",
        "closing_costs": "1520600.00",
        "loan_amount": "45620000.00",
        "interest_rate": "0.061",
        "amortization_years": 30,
        "hold_period_years": 7,
        "exit_cap_rate": "0.0525",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Foundry Lofts",
        "sub_asset_class": "urban_midrise",
        "leasing_mode": "per_unit",
        "unit_count": 148,
        "monthly_rent_per_unit": "2050.00",
        "bed_count": None,
        "monthly_rent_per_bed": None,
        "vacancy_rate": "0.065",
        "other_income_annual": "185000.00",
        "opex_annual": "1272800.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.03",
        "lease_expiration_month": 7,
        "turnover_cost_per_unit_or_bed": "850.00",
        "annual_turnover_rate": "0.55",
        "purchase_price": "42400000.00",
        "closing_costs": "848000.00",
        "loan_amount": "26290000.00",
        "interest_rate": "0.063",
        "amortization_years": 30,
        "hold_period_years": 7,
        "exit_cap_rate": "0.0570",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "The Anthem at Midtown",
        "sub_asset_class": "urban_midrise",
        "leasing_mode": "per_unit",
        "unit_count": 264,
        "monthly_rent_per_unit": "2475.00",
        "bed_count": None,
        "monthly_rent_per_bed": None,
        "vacancy_rate": "0.07",
        "other_income_annual": "422400.00",
        "opex_annual": "2745600.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.035",
        "lease_expiration_month": 7,
        "turnover_cost_per_unit_or_bed": "950.00",
        "annual_turnover_rate": "0.5",
        "purchase_price": "94970000.00",
        "closing_costs": "1899400.00",
        "loan_amount": "60780000.00",
        "interest_rate": "0.0645",
        "amortization_years": 30,
        "hold_period_years": 6,
        "exit_cap_rate": "0.0550",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Canal Street Residences",
        "sub_asset_class": "urban_midrise",
        "leasing_mode": "per_unit",
        "unit_count": 180,
        "monthly_rent_per_unit": "1890.00",
        "bed_count": None,
        "monthly_rent_per_bed": None,
        "vacancy_rate": "0.055",
        "other_income_annual": "198000.00",
        "opex_annual": "1422000.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.028",
        "lease_expiration_month": 7,
        "turnover_cost_per_unit_or_bed": "800.00",
        "annual_turnover_rate": "0.53",
        "purchase_price": "45670000.00",
        "closing_costs": "913400.00",
        "loan_amount": "28770000.00",
        "interest_rate": "0.064",
        "amortization_years": 30,
        "hold_period_years": 8,
        "exit_cap_rate": "0.0605",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Skyline Plaza",
        "sub_asset_class": "urban_midrise",
        "leasing_mode": "per_unit",
        "unit_count": 320,
        "monthly_rent_per_unit": "2620.00",
        "bed_count": None,
        "monthly_rent_per_bed": None,
        "vacancy_rate": "0.075",
        "other_income_annual": "576000.00",
        "opex_annual": "3552000.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.04",
        "lease_expiration_month": 7,
        "turnover_cost_per_unit_or_bed": "1000.00",
        "annual_turnover_rate": "0.48",
        "purchase_price": "131420000.00",
        "closing_costs": "2628400.00",
        "loan_amount": "76220000.00",
        "interest_rate": "0.06",
        "amortization_years": 30,
        "hold_period_years": 7,
        "exit_cap_rate": "0.0500",
        "selling_costs_rate": "0.02",
    },
    {
        "name": "Union Depot Apartments",
        "sub_asset_class": "urban_midrise",
        "leasing_mode": "per_unit",
        "unit_count": 124,
        "monthly_rent_per_unit": "2180.00",
        "bed_count": None,
        "monthly_rent_per_bed": None,
        "vacancy_rate": "0.05",
        "other_income_annual": "167400.00",
        "opex_annual": "1116000.00",
        "expense_growth_rate": "0.03",
        "rent_growth_rate": "0.032",
        "lease_expiration_month": 7,
        "turnover_cost_per_unit_or_bed": "875.00",
        "annual_turnover_rate": "0.51",
        "purchase_price": "39960000.00",
        "closing_costs": "799200.00",
        "loan_amount": "24380000.00",
        "interest_rate": "0.062",
        "amortization_years": 30,
        "hold_period_years": 5,
        "exit_cap_rate": "0.0555",
        "selling_costs_rate": "0.02",
    },
]


def _request(url: str, body: dict | None = None):
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=90) as resp:
        return json.load(resp)


def main(base_url: str) -> None:
    base_url = base_url.rstrip("/")
    existing = {d["name"] for d in _request(f"{base_url}/deals")}
    created = 0
    for deal in DEMO_DEALS:
        if deal["name"] in existing:
            print(f"skip    {deal['name']}")
            continue
        _request(f"{base_url}/deals", deal)
        created += 1
        print(f"created {deal['name']}")
    print(f"done: {created} created, {len(DEMO_DEALS) - created} skipped")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
