"""JSON-ready deal payloads for API tests, matching the seed deals in
backend/seed.py (and tests/engine/fixtures.py) so metrics assertions can
reuse the golden-case numbers in docs/golden-case-derivation.md.
"""

STUDENT_HOUSING_PAYLOAD = {
    "name": "Campus View Student Housing",
    "sub_asset_class": "student_housing",
    "leasing_mode": "per_bed",
    "unit_count": None,
    "monthly_rent_per_unit": None,
    "bed_count": 240,
    "monthly_rent_per_bed": "750.00",
    "vacancy_rate": "0.06",
    "other_income_annual": "36000.00",
    "opex_annual": "620000.00",
    "expense_growth_rate": "0.03",
    "rent_growth_rate": "0.03",
    "lease_expiration_month": 8,
    "turnover_cost_per_unit_or_bed": "350.00",
    "annual_turnover_rate": "0.85",
    "purchase_price": "21500000.00",
    "closing_costs": "430000.00",
    "loan_amount": "14000000.00",
    "interest_rate": "0.0625",
    "amortization_years": 30,
    "hold_period_years": 7,
    "exit_cap_rate": "0.058",
    "selling_costs_rate": "0.02",
}

SUBURBAN_GARDEN_PAYLOAD = {
    "name": "Willowbrook Suburban Garden",
    "sub_asset_class": "suburban_garden",
    "leasing_mode": "per_unit",
    "unit_count": 180,
    "monthly_rent_per_unit": "1450.00",
    "bed_count": None,
    "monthly_rent_per_bed": None,
    "vacancy_rate": "0.05",
    "other_income_annual": "54000.00",
    "opex_annual": "980000.00",
    "expense_growth_rate": "0.03",
    "rent_growth_rate": "0.025",
    "lease_expiration_month": 6,
    "turnover_cost_per_unit_or_bed": "900.00",
    "annual_turnover_rate": "0.55",
    "purchase_price": "28800000.00",
    "closing_costs": "576000.00",
    "loan_amount": "18700000.00",
    "interest_rate": "0.06",
    "amortization_years": 30,
    "hold_period_years": 10,
    "exit_cap_rate": "0.055",
    "selling_costs_rate": "0.02",
}

URBAN_MIDRISE_PAYLOAD = {
    "name": "Meridian Urban Mid-Rise",
    "sub_asset_class": "urban_midrise",
    "leasing_mode": "per_unit",
    "unit_count": 95,
    "monthly_rent_per_unit": "2100.00",
    "bed_count": None,
    "monthly_rent_per_bed": None,
    "vacancy_rate": "0.07",
    "other_income_annual": "42000.00",
    "opex_annual": "870000.00",
    "expense_growth_rate": "0.03",
    "rent_growth_rate": "0.02",
    "lease_expiration_month": 5,
    "turnover_cost_per_unit_or_bed": "1500.00",
    "annual_turnover_rate": "0.5",
    "purchase_price": "32000000.00",
    "closing_costs": "640000.00",
    "loan_amount": "20800000.00",
    "interest_rate": "0.0615",
    "amortization_years": 30,
    "hold_period_years": 10,
    "exit_cap_rate": "0.05",
    "selling_costs_rate": "0.02",
}
